### ISSUE TITLE
Add German copy for website

### ISSUE THREAD

**Issue by candu** [international-jugger-council/ijc-website#23]
**Description**
We don't yet have German copy for the website, but we at least have a precedent in international-jugger-council/ijc-website#6 for integrating multilingual copy into the IJC website.

This is a tracking task for progress here.

**Acceptance Criteria**
- [x] get copy written for German version of site;
- [x] remove captive "hey, we're translating this!" modal from German language;
- [ ] add German copy to:
  - [ ] main page;
  - [ ] about;
  - [ ] play;
- [ ] make sure nav items match headings on pages.

**Comment by ArturoAresius** [comment]
It should also be made sure that the "please help us translate" pop up is moved to appear when clicking a 4th language button named "others", so that people can offer us help to get the work done
