### ISSUE TITLE
Let's host the site on github pages to automate deployment

### ISSUE THREAD

**Issue by valkyriesavage** [international-jugger-council/ijc-website#5]
**Description**
There's no reason necessarily to host the site ourselves on the Savages' Linode box, since it is a static resource. We can just as easily set up automated deployment to github pages and save ourselves that particular headache.

**Acceptance Criteria**
- [x] github pages enabled on `gh-pages` branch
- [x] configure custom domain (`juggercouncil.org`) in settings, and ensure `CNAME` file is included in site
- [x] create `.travis-ci.yml` file that runs `npm run build` on new pushes to master, and updates `gh-pages` branch
- [x] `juggercouncil.org` DNS configuration on Linode updated to point to github pages

**Comment by candu** [comment]
Update: site transition to Github Pages is complete! 🎉
